import type { NextPage } from "next";
import Head from "next/head";

// COMPONENTS
import { Main } from "@components/Main/Main";
import { About } from "@components/Abount/About";
import { Skills } from "@components/Skills/Skills";
import { Projects } from "@components/Projects/Projects";
import { Contact } from "@components/Contact/Contact";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fullstack Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main id="main">
        <Main />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </main>
    </>
  );
};

export default Home;
