import type { NextPage } from "next";
import Head from "next/head";

// COMPONENTS
// import { Navbar } from "../components/Navbar/Navbar";
import { Main } from "../components/Main/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fullstack Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main />
      <Main />
    </div>
  );
};

export default Home;
